services:
  gerenciador:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gerenciador
    environment:
      DB_HOST: db
    ports:
      - "8080:8080"
    networks:
      - gerenciar-network
    depends_on:
      - db
    restart: on-failure
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: manager
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - gerenciar-network
    command: --lower_case_table_names=1
networks:
  gerenciar-network:
    driver: bridge